# Generated by Django 4.2.29 on 2026-03-18 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_tr", models.CharField(max_length=200, null=True)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "İçerik Kategorisi",
                "verbose_name_plural": "İçerik Kategorileri",
            },
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("twitter", "Twitter/X"),
                            ("facebook", "Facebook"),
                        ],
                        max_length=15,
                        unique=True,
                    ),
                ),
                ("url", models.URLField()),
                ("username", models.CharField(max_length=100)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sosyal Medya Bağlantısı",
                "verbose_name_plural": "Sosyal Medya Bağlantıları",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("title_tr", models.CharField(max_length=300, null=True)),
                ("title_en", models.CharField(max_length=300, null=True)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
                ("description_tr", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="videos/thumbnails/"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("vimeo", "Vimeo"),
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                            ("other", "Diğer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("video_url", models.URLField()),
                ("embed_code", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="content.contentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videolar",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("title_tr", models.CharField(max_length=300, null=True)),
                ("title_en", models.CharField(max_length=300, null=True)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("excerpt", models.CharField(blank=True, max_length=500)),
                ("excerpt_tr", models.CharField(blank=True, max_length=500, null=True)),
                ("excerpt_en", models.CharField(blank=True, max_length=500, null=True)),
                ("body", models.TextField()),
                ("body_tr", models.TextField(null=True)),
                ("body_en", models.TextField(null=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("published", "Yayında"),
                            ("archived", "Arşivlenmiş"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                (
                    "meta_title_tr",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "meta_title_en",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("meta_description", models.CharField(blank=True, max_length=500)),
                (
                    "meta_description_tr",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "meta_description_en",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="content.contentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Makale",
                "verbose_name_plural": "Makaleler",
                "ordering": ["-published_at"],
            },
        ),
    ]
