# Generated by Django 4.2.29 on 2026-03-18 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_tr", models.CharField(max_length=200, null=True)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("description_tr", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("name_tr", models.CharField(max_length=300, null=True)),
                ("name_en", models.CharField(max_length=300, null=True)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("description", models.TextField()),
                ("description_tr", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "short_description_tr",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "short_description_en",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("physical", "Fiziksel Ürün"),
                            ("digital", "Dijital Ürün"),
                            ("affiliate", "Affiliate Ürün"),
                        ],
                        default="physical",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("active", "Aktif"),
                            ("archived", "Arşivlenmiş"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "price_try",
                    models.DecimalField(
                        decimal_places=2, help_text="TRY fiyat", max_digits=10
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2, help_text="USD fiyat", max_digits=10
                    ),
                ),
                (
                    "compare_at_price_try",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Karşılaştırma fiyatı (TRY) - indirim göstermek için",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "compare_at_price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Karşılaştırma fiyatı (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("track_stock", models.BooleanField(default=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("affiliate_url", models.URLField(blank=True)),
                (
                    "affiliate_commission",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "digital_file",
                    models.FileField(
                        blank=True, null=True, upload_to="digital_products/"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                (
                    "meta_title_tr",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "meta_title_en",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("meta_description", models.CharField(blank=True, max_length=500)),
                (
                    "meta_description_tr",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "meta_description_en",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="products/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Görseli",
                "verbose_name_plural": "Ürün Görselleri",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Yorumu",
                "verbose_name_plural": "Ürün Yorumları",
                "unique_together": {("product", "user")},
            },
        ),
    ]
